export const data = [
    {
      question: "Quantas temporadas tem Game of thrones",
      option1: "8 temporadas",
      option2: "10 temporadas",
      option3: "6 temporadas",
      option4: "7 temporadas",
      ans: 1,
    },
    {
      question: "Qual desses jogos ganho o GOTY 2018",
      option1: "Red Dead Redemption 2",
      option2: "Monster Hunter: World",
      option3: "God of war",
      option4: "Spider man",
      ans: 3,
    },
    {
      question: "Forrest Gump ganhou quantos oscar",
      option1: "1 oscar",
      option2: "3 oscar",
      option3: "5 oscar",
      option4: "6 oscar",
      ans: 4,
    },
    {
      question: "Quem é o protagonista de red dead redemption 2",
      option1: "John Marston",
      option2: "Arthur Morgan",
      option3: "Joel",
      option4: "Kratos",
      ans: 2,
    },
    {
      question: "Quem é o protagonista de the walking dead",
      option1: "Rick Grimes",
      option2: "Jon Snow",
      option3: "Tiryon Lannister ",
      option4: "Walter White(Heisenberg)",
      ans: 1,
    },
  ];